import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Error-404",
  description: "Generated by create next app",
};

export default function Error() {
  return (
    <>
      <div className="flex h-screen flex-col items-center justify-center text-white">
        <div className="text-center">
          {/* <Image
            src="/errorImg.svg"
            width={500}
            height={500}
            alt="error"
            className="mb-4"
          /> */}
          <div className="flex w-full items-center justify-center gap-4">
            <h1 className="mb-6 text-4xl font-bold text-[#FF0080]">404 |</h1>
            <h1 className="mb-6 text-4xl font-bold">Ops!</h1>
          </div>
          <h6 className="text-xl">
            Não conseguimos encontrar o perfil da modelo que você procurava.
          </h6>
        </div>
      </div>
    </>
  );
}
